### ISSUE TITLE
Input Error Messages, Help

### ISSUE THREAD

**Issue by wwone** [faceless2/json#1]
First of all, I quite like this product. I have simple JSON inputs to various programs that I have written in Java. This product makes the matter very simple to use.

These are not necessarily issues, but I need help with:

1) If I make a syntax error in the JSON input (easy to do, sorry), the Exceptions thrown don't really help, because I don't see the context of the error. Some surrounding input text would be helpful, such as 'error near: --"my stuff",""my stuff wrong because of extra quote"--'

2) I read in simple JSON Strings that are modified in-place in my code. Can a 'Json' object containing a single String be modified in-memory? I cannot figure out how from the JavaDoc.

**Comment by faceless2** [comment]
Thanks Bob! Nice feedback. We were aiming for simple.

First point is a good one, a bit of context is useful especially on large objects. We'll put this in. Second point, no, not presently - objects are immutable. However, there's no real need for it to be this way, so I'l patch that in too when I get a minute next week.

**Comment by wwone** [comment]
Thanks for the quick feedback. Actually, keeping the List and Map views as
immutable is something I should regard as  a feature. The fact that the
current JAR imposes this limit has actually helped me in my coding. The
original code I wrote performed modify-in-place for key/value sets. Yes
this would cause me to try to PUT stuff into the Json object, and the
immutability seemed to be a 'problem'. After much rethinking, I have
completely redesigned my code to use the immutability to my advantage and
not do the in-place (kluge) approach. Keep in mind that I am using JSON as
read-only information anyway and am not creating Json objects to write out
somewhere.

So, no hurry on changing your fundamental code. Perhaps there could be a
way to offer both mutable and immutable views, but I wonder if you might
not want just any old stuff to be pushed into an already-created Json
object. Not for me to say, it is your design, and I'm now dealing with the
matter just fine.

Regarding the parsing errors, yes please. I looked at the code, and this
may be a heroic enhancement. But it would indeed be nice. The other JSON
parsers I've used (Jackson comes to mind) were quite good at pinpointing
the syntax error. I love JSON as a format, better than the XML I hacked
away with for many years, but it is still not really human-friendly.

Keep up the good work!

**Comment by faceless2** [comment]
Done. There is a new method, Json.setValue(Json src), which will copy the value from the "src" object to this object, eg.
```java
Json a = new Json(999);
Json b = new Json("string");
a.setValue(b);
System.out.println(a);  // "string"
```
And any errors reported during reading are given a line/column number and the previous 30 characters read. Thanks for the suggestions.

**Comment by wwone** [comment]
THANK YOU, greatly appreciate your work. The error messages are very helpful.
