### ISSUE TITLE
Question: What maven dependency to be included in spring project

### ISSUE THREAD

**Issue by mhatrepratik11** [faceless2/json#2]
Hello team.

I want to use this library for 1 of my use case. I am using Java-Spring Boot project with Maven and I am confused what dependency to be included in my pom.xml.

**Use Case:** 
1) I have a JSON structure which needs to be transformed to the COSE. 
2) I should get JSON back if COSE provided.

**Note:** I have a private key and public key available with me in the .pem files.

**Thanks in Advance!**

**Comment by faceless2** [comment]
We've never set up a Maven project for this, so until we do (it's probably a good idea), you would just need to download the Jars yoursself.

Converting between JSON and COSE is trivial, see the examples on the README.md file (at https://github.com/faceless2/json/), or:

```Java
Json json = Json.read("{\"test\":123}");  
// Json json = Json.reaad(new JsonReader().setInput("input.json"));  // alternative to line above
ByteBuffer cbor = json.toCbor();
OutputStream out = new FIleOutputStream("out.cbor");
out.write(new CborWriter().setOutput(out));
out.close();
```

**Comment by mhatrepratik11** [comment]
Thanks for your reply and clarification @faceless2. I will move forward with the jars then.
